---

replicaCount: 3

image_repo: "jgraph/drawio"

port: 8080

extUrl: "drawio.yourdomain.com"

create_route: false
create_networkpolicy: true
createIngress: true

resources:
  limits:
    cpu: "500m"
    memory: "1024Mi"
  requests:
    cpu: "250m"
    memory: "512Mi"

cert:
  # requestCertificate can be set to true, if you have cert-manager installed and want to create certificates
  requestCertificate: true
  # kind describes the kind of cert-manager issuer you use, Issuer or ClusterIssuer
  kind: "ClusterIssuer"
  # name is the name of the issuer
  name: ""
  # secretName ist the name of the secret for the certificate | standard is acme-cert-drawio
  secretName: "acme-cert-drawio"

ingress:
  # If ingress is true, route has to be false
  # createIngress has to be set to true, if you want to create an ingress
  createIngress: true
  # secretName is the name of the secret for the ingress | standard is acme-cert-drawio
  secretName: acme-cert-drawio
...
