---

replicaCount: 3

image_repo: "jgraph/drawio"

port: 8080

extUrl: "drawio.yourdomain.com"

create_route: true
create_networkpolicy: true

resources:
  limits:
    cpu: "500m"
    memory: "1024Mi"
  requests:
    cpu: "250m"
    memory: "512Mi"
...
