---
# replicaCount specifies the amount of replicas the deployment should have
replicaCount: 3

# imageRepo is the image repository to pull the container image from
imageRepo: "jgraph/drawio"

# port that's needed for draw.io
port: 8080

# extURL is the URL where draw.io is reachable from, no need to add https or www
extUrl: "drawio.yourdomain.com"

# create_Route has to be set to true if you want to create a route
createRoute: false
# createNetworkpolicy has to be set to true if you want to create a networkpolicy
createNetworkpolicy: true

resources:
  limits:
    # resources.limits.cpu ist the maximum CPU usage of each container, it cant exceed the given CPU usage
    cpu: "500m"
    # resources.limits.memory is the maximum amount of RAM for each container, if it reaches the limit the pod gets OOM killed
    memory: "1024Mi"
  requests:
    # resources.requests.cpu ist the requested CPU usage of each container, it can exceed the CPU request
    cpu: "250m"
    # resources.requests.memory is the requested amount of RAM for each container
    memory: "512Mi"

cert:
  # cert.requestCertificate can be set to true, if you have cert-manager installed and want to create certificates
  requestCertificate: true
  # cert.kind describes the kind of cert-manager issuer you use, Issuer or ClusterIssuer
  kind: "ClusterIssuer"
  # cert.name is the name of the issuer
  name: ""
  # cert.secretName ist the name of the secret for the certificate | standard is acme-cert-drawio
  secretName: "acme-cert-drawio"

ingress:
  # If ingress is true, route has to be false
  # ingress.createIngress has to be set to true, if you want to create an ingress
  createIngress: true
  # ingress.secretName is the name of the secret for the ingress | standard is acme-cert-drawio
  secretName: acme-cert-drawio
...
